### ISSUE TITLE
 Error when VU is installed in another directory

### ISSUE THREAD

**Issue by rierei** [Dendari92/vulauncher#14]
The way the VU starts was now changed. I no longer need it to be installed at the root of the game. Then having the client in another folder, the VU Launcher returns the following message :

> Cound not find "vu.exe" in the Battlefield 3 directory! Please verify Venice Unleashed is installed correctly .

**Comment by Dendari92** [comment]
Thanks for the report. Just updated to a [new version](https://github.com/Dendari92/vulauncher/releases/tag/v1.1.1), it should be fixed.
